## Description
When host game is selected and a move is attempted to be made, a series of different error messages, all related to TurnManager show up.

## Expected Behavior

A move should be recorded and sent to the server and a message must be displayed, saying waiting for the server.

## Current Behavior

Whenever a move is attempted to be made, a series of error messages are made.

All the messages are originating with TurnManagement

## Steps to Reproduce

Provide detailed steps for reproducing the issue.

 1. Click host game and upload JSON
 2. Once the chessboard loads, click on the associated piece and make a move.

## Failure Logs

NOTE: One error lead to other errors being discovered, as a result of similar issues.

ERROR#1
java.lang.NullPointerException: Cannot invoke "oogasalad.Server.SessionManagement.GameSession.turns()" because the return value of "oogasalad.Server.SessionManagement.GameSessionService.getSession(String)" is null
	at oogasalad/oogasalad.Server.Controllers.TurnController.getEndConditions(TurnController.java:157) ~[classes/:na]

ERROR#2
oogasalad.GamePlayer.Board.TurnManagement.RemoteTurnManager - Cannot deserialize value of type `java.lang.Boolean` from Array value (token `JsonToken.START_ARRAY`)

ERROR#3
oogasalad.GamePlayer.Board.TurnManagement.RemoteTurnManager - For input string: "["java.util.LinkedHashMap",{"timestamp":["java.util.Date",1651199494709],"status":405,"error":"Method Not Allowed","trace":"org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported"

ERROR#4
2022-04-29 00:51:29.605 ERROR 75800 --- [nio-8080-exec-4] o.G.B.TurnManagement.RemoteTurnManager   : For input string: "["java.util.LinkedHashMap",{"timestamp":["java.util.Date",1651207889584],"status":404,"error":"Not Found","message":"No message available","path":"/turns/current/"}]"

ERROR#5
01:23:51.030 [JavaFX Application Thread] ERROR oogasalad.GamePlayer.Board.TurnManagement.RemoteTurnManager - Could not resolve type id 'java.util.Collections$UnmodifiableMap' as a subtype of `java.util.Map<java.lang.Integer,java.lang.Double>`: Configured `PolymorphicTypeValidator` (of type `com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator`) denied resolution

## Hypothesis for Fixing the Bug

Since all of the issues are arising from turn manager, I decided to test that. We know that the turn manager gets and returns valid responses as we have extensively tested it already and we use the same local code for the server implementation.

The test I implemented is a simple test doing a linear test with a remote turn manager. While I could have done a more exhaustive test, I wanted this to be minimal to not drastically increase line coverage during the DEMO phase.